---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: '172.230.22.155'
      api_key: LUFRPT13L3g4Z1ErUklDM0I1c3gzTnBlVXh5NyszMTA9bGpIVThyVlUxbEJxMTIxYytkQi82Q09RTndBR3ZDemZVdHg2aGk1V3ZrNzY3RkdqckxjWURxWXFOZExtbGxxMQ==

  tasks:
    - name: Create First Security Rule
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'Prod http'
        source_zone: ['any']
        destination_zone: ['any']
        source_ip: ['server01']
        destination_ip: ['server02']
        application: ['any']
        service: ['application-default']
        action: 'allow'
        tag_name: ['Prod']

    - name: Commit
      panos_commit:
        provider: '{{ palo_provider }}'
