---
- name: Palo Alto Playbook
  hosts: all
  gather_facts: false
  connection: local
  collections:
    - paloaltonetworks.panos
  vars:
    palo_provider:
      ip_address: '172.230.22.155'
      api_key: LUFRPT1YTHNkL21SVGR2TTF6MHJtTFYxVDlDWXA5QU09bGpIVThyVlUxbEJxMTIxYytkQi82T3FRaythRDJYQ0hXNytTWFZhR0J5TjRNRk05ZWh1dTlyNXNzSE9oNmdFOA==
  tasks:
    - name: Create Server Object
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: 'server5'
        value: '172.16.5.50/32'
        description: 'cmp'   
    - name: Commit
      panos_commit:
        provider: '{{ palo_provider }}'
