---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos


  vars:
    palo_provider:
      ip_address: '172.230.22.155'
      api_key: LUFRPT13L3g4Z1ErUklDM0I1c3gzTnBlVXh5NyszMTA9bGpIVThyVlUxbEJxMTIxYytkQi82Q09RTndBR3ZDemZVdHg2aGk1V3ZrNzY3RkdqckxjWURxWXFOZExtbGxxMQ==

  tasks:
    - name: Create tag object Prod
      panos_tag_object:
        provider: '{{ palo_provider }}'
        name: 'Prod'
        color: 'red'
        comments: 'Prod Environment'

    - name: Commit
      panos_commit:
        provider: '{{ palo_provider }}'
